### PR TITLE
Add a new widget: RadioSelectButtonGroup

### PR DESCRIPTION
**Pull request by FlipperPA**
This PR adds a widget, `RadioSelectButtonGroup`, which allows display of radio buttons as a mobile friendly Bootstrap4 rendering. Documentation to follow shortly...

### CODE REVIEW

**Comment by FlipperPA** [comment]
Fixes #102

**Comment by FlipperPA** [comment]
Hmmm, TravisCI seems to be failing on Python 2.7 installing `tox`.

**Comment by FlipperPA** [comment]
@dyve Can you have a look at why `tox` died on 2.7? It worked for all Python 3 versions.

**Comment by dyve** [comment]
Hi, 2 weeks on summer holiday now. Will check after that.

**Comment by dyve** [comment]
Thanks Tim!

**Comment by dyve** [comment]
Might need a little documentation.

**Pull request merged**
