### PR TITLE
FileInput Label Rendering Fix

### PR DESCRIPTION
**Pull request by ArnavVarshney**
Addresses issue #212 

Add a fix_file_input_label function to renderers.py to add a new line after the label for FileInput widget.

[Rendering after the fix](https://i.imgur.com/NOZuRkp.jpg)

### CODE REVIEW

**Comment by xi** [comment]
The fix itself looks good to me, but you also added a bunch of unrelated files. Can you please remove them?

**Comment by ArnavVarshney** [comment]
@xi How exactly do I do that now?

**Comment by dyve** [comment]
One more to go (pyenv.cfg) 👍

**Comment by ArnavVarshney** [comment]
@dyve Yup done!

**Comment by dyve** [comment]
🎉

**Pull request merged**
