### PR TITLE
input-group changes in beta 3

### PR DESCRIPTION
**Pull request by jproffitt**
Beta 3 refactored the markup for `input-group`s: https://getbootstrap.com/docs/4.0/migration/#input-groups

In summary:

- Need `input-group-prepend` or `input-group-append` instead of `input-group-addon`.
- Need an inner span to the add-on with the class `input-group-text`, unless you have a button for the add-on, in which case you can omit the span.

So for a add-on before with a button, the html used to be:

```
<span class="input-group-btn">
    <a href="#" class="btn">A button</a>
</span>
```

But now it should be:

```
<span class="input-group-prepend">
    <a href="#" class="btn">A button</a>
</span>
```

And for any other kind of text the html used to be:

```
<span class="input-group-addon">
    Some add-on text
</span>
```

But now it should be:

```
<div class="input-group-prepend">
    <span class="input-group-text">
        <a href="#" class="btn">A button</a>
    </span>
</div>
```

I hope my change makes sense. Basically, you can no longer change the class for `input-group-prepend` or `input-group-append`, but you can change the class for the inner span. Which defaults to `input-group-text`. And if you want to remove the span altogether, like for buttons, you can just set it to `None`.

### CODE REVIEW

**Comment by jproffitt** [comment]
Sorry, I just noticed the build failed. I'll fix the tests soon

**Comment by jproffitt** [comment]
Ok, this PR is ready to go. Sorry, I forgot about fixing the tests until just now.

**Comment by dyve** [comment]
Thanks!

**Comment by JonathanSeguin** [comment]
@dyve Thank you! Any chance we can roll out another PyPi package?

**Pull request merged**
