### PR TITLE
Fix missing attribute when button having href

### PR DESCRIPTION
**Pull request by cjltsod**
Sample code is

> {% bootstrap_button 'DO_HREF' button_type='button' button_class='btn-primary' href='/SOMEWHERE' %}

### CODE REVIEW

**Comment by cjltsod** [comment]
Ref: [Bootstrap 4 Buttons](https://getbootstrap.com/docs/4.1/components/buttons/)
Seems the test needs to be fix too.

**Comment by dyve** [comment]
Hi @cjltsod, a `button` with a `href` element is invalid HTML. So the example code would be a user error, which is something we should not silently fix. Do you think we should throw an error if `button_type='button'` and `href` are specified?

**Comment by cjltsod** [comment]
I got your point. 
It's the best way that throwing error when `href` specified and `button_type` not set to `link`.

**Comment by dyve** [comment]
Continued in #110, thanks.

**Pull request closed without merging**
