### PR TITLE
Field errors and help texts

### PR DESCRIPTION
**Pull request by jproffitt**
The validation classes for fields have been moved to the input elements themselves, and renamed to `is-valid` and `is-invalid`: https://getbootstrap.com/docs/4.0/components/forms/

The help text class has been renamed from `help-block` to `form-text text-muted`: https://getbootstrap.com/docs/4.0/components/forms/#help-text

The validation error message class has been changed from using the `help-block` to a new class, `invalid-feedback`: https://getbootstrap.com/docs/4.0/components/forms/#server-side

This PR fixes those 3 things.

### CODE REVIEW

**Comment by jieter** [comment]
@jproffitt Thanks for working on this, but it makes the tests fail. Can you try to fix the tests?

**Comment by jieter** [comment]
@jproffitt thanks for working on this. After your commit, I made some changes to the structure and merged another PR resulting in conflicts. Can you also have a look?

**Comment by jproffitt** [comment]
@jieter I think I just fixed the conflict.

**Comment by jieter** [comment]
Thanks!

**Pull request merged**
