### PR TITLE
Adapt checkbox rendering for Bootstrap4

### LINKED ISSUE #95: Different div class for checkboxes
There is a different div class in the Bootstrap's docs for checkboxes.

https://getbootstrap.com/docs/4.1/components/forms/#overview

Now it's "form-group form-check" but the library generates only the "form-group" div.

### PR DESCRIPTION
**Pull request by sedrubal**
Fixes #95 

It may be a bit hacky but it should work...

### CODE REVIEW

**Comment by dyve** [comment]
Could we have a test that prevents regression?

**Comment by dyve** [comment]
Thanks @sedrubal.
I have limited experience with using BeautifulSoup for testing. @jieter your opinion?

**Comment by jieter** [comment]
in django-tables2, we use lxml, but I think BeautifulSoup has a more user friendly API. As long as one is chosen, which one doesn't matter to me.

**Comment by jieter** [comment]
This is a good illustration why using something like BeautifulSoup is a very good idea:

https://github.com/zostera/django-bootstrap4/pull/104/files#diff-e11ea24805bba77a267e4eb0e8650bbbL697

**Pull request merged**
