### PR TITLE
Change to beta 2

### PR DESCRIPTION
**Pull request by mcparadip**
Bootstrap 4.0.0-beta.2 has been released.

### CODE REVIEW

**Comment by FlipperPA** [comment]
Awesome, can we get `0.0.4` dropped, perhaps with the updated docs merged? Thanks for your efforts!

**Comment by mcparadip** [comment]
Any update on this?

**Comment by nikolas** [comment]
This should be merged. But note that you can do this update outside of django-bootstrap4, which is what I'm doing since `bootstrap_css_url` is broken at the moment: https://github.com/zostera/django-bootstrap4/issues/33

**Comment by dyve** [comment]
Thanks!

**Pull request merged**
